### ISSUE TITLE
What is the rationale behind using 10 here?

### ISSUE THREAD

**Issue by cvank** [pmadala/Java_Learning#23]
https://github.com/pmadala/Java_Learning/blob/757e70db0db27a4ff1cf2615d59b16d78fc08ab7/Multithreading/src/main/java/org/Multithreading/task2/TaskExecutor.java#L44

**Comment by pmadala** [comment]
Fixed in https://github.com/pmadala/Java_Learning/commit/3a2580a6a8596ac8b8ace13c8178b753ef4711f4
